-- Generated by tools/dbcpatch. Apply to acore_world with matching Spell.dbc and Item.dbc.

DELETE FROM `trainer_spell` WHERE `SpellId` = 80860;
INSERT INTO `trainer_spell` (`TrainerId`,`SpellId`,`MoneyCost`,`ReqSkillLine`,`ReqSkillRank`,`ReqAbility1`,`ReqAbility2`,`ReqAbility3`,`ReqLevel`,`VerifiedBuild`)
SELECT DISTINCT `TrainerId`,80860,5000,0,0,0,0,0,10,12340 FROM `trainer_spell` WHERE `SpellId` = 33388;

DELETE FROM `npc_vendor` WHERE `item` BETWEEN 900100 AND 900164;
DELETE FROM `item_template` WHERE `entry` BETWEEN 900100 AND 900164;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 90001 AND 90065;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 90001 AND 90065;

-- Pinto Bridle -> Reins of the Tiny Pinto (Katie Hunter)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90002;
DELETE FROM `creature_template` WHERE `entry`=90002;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=307;
UPDATE `swp_mount_creature` SET `entry`=90002,`name`='Tiny Pinto'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90002,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=307;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=2414;
UPDATE `swp_mount_item` SET `entry`=900101,`name`='Reins of the Tiny Pinto',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81000; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=384 AND `item`=900101; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (384,0,900101,0,0,0,12340);

-- Chestnut Mare Bridle -> Reins of the Tiny Chestnut Mare (Katie Hunter)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90003;
DELETE FROM `creature_template` WHERE `entry`=90003;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=4269;
UPDATE `swp_mount_creature` SET `entry`=90003,`name`='Tiny Chestnut Mare'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90003,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=4269;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=5655;
UPDATE `swp_mount_item` SET `entry`=900102,`name`='Reins of the Tiny Chestnut Mare',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81001; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=384 AND `item`=900102; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (384,0,900102,0,0,0,12340);

-- Brown Horse Bridle -> Reins of the Tiny Brown Horse (Katie Hunter)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90004;
DELETE FROM `creature_template` WHERE `entry`=90004;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=284;
UPDATE `swp_mount_creature` SET `entry`=90004,`name`='Tiny Brown Horse'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90004,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=284;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=5656;
UPDATE `swp_mount_item` SET `entry`=900103,`name`='Reins of the Tiny Brown Horse',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81002; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=384 AND `item`=900103; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (384,0,900103,0,0,0,12340);

-- Gray Ram -> Reins of the Tiny Gray Ram (Veron Amberstill)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90005;
DELETE FROM `creature_template` WHERE `entry`=90005;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=4710;
UPDATE `swp_mount_creature` SET `entry`=90005,`name`='Tiny Gray Ram'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90005,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=4710;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=5864;
UPDATE `swp_mount_item` SET `entry`=900104,`name`='Reins of the Tiny Gray Ram',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81003; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=1261 AND `item`=900104; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (1261,0,900104,0,0,0,12340);

-- Brown Ram -> Reins of the Tiny Brown Ram (Veron Amberstill)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90006;
DELETE FROM `creature_template` WHERE `entry`=90006;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=4779;
UPDATE `swp_mount_creature` SET `entry`=90006,`name`='Tiny Brown Ram'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90006,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=4779;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=5872;
UPDATE `swp_mount_item` SET `entry`=900105,`name`='Reins of the Tiny Brown Ram',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81004; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=1261 AND `item`=900105; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (1261,0,900105,0,0,0,12340);

-- White Ram -> Reins of the Tiny White Ram (Veron Amberstill)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90007;
DELETE FROM `creature_template` WHERE `entry`=90007;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=4777;
UPDATE `swp_mount_creature` SET `entry`=90007,`name`='Tiny White Ram'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90007,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=4777;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=5873;
UPDATE `swp_mount_item` SET `entry`=900106,`name`='Reins of the Tiny White Ram',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81005; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=1261 AND `item`=900106; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (1261,0,900106,0,0,0,12340);

-- Horn of the Timber Wolf -> Reins of the Tiny Timber Wolf (Ogunaro Wolfrunner)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90008;
DELETE FROM `creature_template` WHERE `entry`=90008;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=358;
UPDATE `swp_mount_creature` SET `entry`=90008,`name`='Tiny Timber Wolf'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90008,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=358;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=1132;
UPDATE `swp_mount_item` SET `entry`=900107,`name`='Reins of the Tiny Timber Wolf',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81006; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=3362 AND `item`=900107; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (3362,0,900107,0,0,0,12340);

-- Horn of the Dire Wolf -> Reins of the Tiny Dire Wolf (Ogunaro Wolfrunner)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90009;
DELETE FROM `creature_template` WHERE `entry`=90009;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=4271;
UPDATE `swp_mount_creature` SET `entry`=90009,`name`='Tiny Dire Wolf'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90009,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=4271;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=5665;
UPDATE `swp_mount_item` SET `entry`=900108,`name`='Reins of the Tiny Dire Wolf',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81007; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=3362 AND `item`=900108; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (3362,0,900108,0,0,0,12340);

-- Horn of the Brown Wolf -> Reins of the Tiny Brown Wolf (Ogunaro Wolfrunner)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90010;
DELETE FROM `creature_template` WHERE `entry`=90010;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=4272;
UPDATE `swp_mount_creature` SET `entry`=90010,`name`='Tiny Brown Wolf'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90010,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=4272;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=5668;
UPDATE `swp_mount_item` SET `entry`=900109,`name`='Reins of the Tiny Brown Wolf',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81008; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=3362 AND `item`=900109; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (3362,0,900109,0,0,0,12340);

-- Horn of the Black Wolf -> Reins of the Tiny Black Wolf (Ogunaro Wolfrunner)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90011;
DELETE FROM `creature_template` WHERE `entry`=90011;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=356;
UPDATE `swp_mount_creature` SET `entry`=90011,`name`='Tiny Black Wolf'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90011,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=356;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=46099;
UPDATE `swp_mount_item` SET `entry`=900110,`name`='Reins of the Tiny Black Wolf',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81009; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=3362 AND `item`=900110; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (3362,0,900110,0,0,0,12340);

-- Gray Kodo -> Reins of the Tiny Gray Kodo (Harb Clawhoof)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90012;
DELETE FROM `creature_template` WHERE `entry`=90012;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=12149;
UPDATE `swp_mount_creature` SET `entry`=90012,`name`='Tiny Gray Kodo'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90012,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=12149;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=15277;
UPDATE `swp_mount_item` SET `entry`=900111,`name`='Reins of the Tiny Gray Kodo',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81010; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=3685 AND `item`=900111; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (3685,0,900111,0,0,0,12340);

-- Brown Kodo -> Reins of the Tiny Brown Kodo (Harb Clawhoof)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90013;
DELETE FROM `creature_template` WHERE `entry`=90013;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=11689;
UPDATE `swp_mount_creature` SET `entry`=90013,`name`='Tiny Brown Kodo'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90013,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=11689;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=15290;
UPDATE `swp_mount_item` SET `entry`=900112,`name`='Reins of the Tiny Brown Kodo',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81011; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=3685 AND `item`=900112; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (3685,0,900112,0,0,0,12340);

-- White Kodo -> Reins of the Tiny White Kodo (Harb Clawhoof)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90014;
DELETE FROM `creature_template` WHERE `entry`=90014;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=34155;
UPDATE `swp_mount_creature` SET `entry`=90014,`name`='Tiny White Kodo'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90014,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=34155;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=46100;
UPDATE `swp_mount_item` SET `entry`=900113,`name`='Reins of the Tiny White Kodo',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81012; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=3685 AND `item`=900113; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (3685,0,900113,0,0,0,12340);

-- Reins of the Striped Nightsaber -> Reins of the Tiny Striped Nightsaber (Lelanai)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90015;
DELETE FROM `creature_template` WHERE `entry`=90015;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=7690;
UPDATE `swp_mount_creature` SET `entry`=90015,`name`='Tiny Striped Nightsaber'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90015,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=7690;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8629;
UPDATE `swp_mount_item` SET `entry`=900114,`name`='Reins of the Tiny Striped Nightsaber',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81013; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4730 AND `item`=900114; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4730,0,900114,0,0,0,12340);

-- Reins of the Striped Frostsaber -> Reins of the Tiny Striped Frostsaber (Lelanai)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90016;
DELETE FROM `creature_template` WHERE `entry`=90016;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=6074;
UPDATE `swp_mount_creature` SET `entry`=90016,`name`='Tiny Striped Frostsaber'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90016,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=6074;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8631;
UPDATE `swp_mount_item` SET `entry`=900115,`name`='Reins of the Tiny Striped Frostsaber',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81014; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4730 AND `item`=900115; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4730,0,900115,0,0,0,12340);

-- Reins of the Spotted Frostsaber -> Reins of the Tiny Spotted Frostsaber (Lelanai)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90017;
DELETE FROM `creature_template` WHERE `entry`=90017;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=7687;
UPDATE `swp_mount_creature` SET `entry`=90017,`name`='Tiny Spotted Frostsaber'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90017,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=7687;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8632;
UPDATE `swp_mount_item` SET `entry`=900116,`name`='Reins of the Tiny Spotted Frostsaber',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81015; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4730 AND `item`=900116; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4730,0,900116,0,0,0,12340);

-- Reins of the Striped Dawnsaber -> Reins of the Tiny Striped Dawnsaber (Lelanai)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90018;
DELETE FROM `creature_template` WHERE `entry`=90018;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=35168;
UPDATE `swp_mount_creature` SET `entry`=90018,`name`='Tiny Striped Dawnsaber'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90018,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=35168;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=47100;
UPDATE `swp_mount_item` SET `entry`=900117,`name`='Reins of the Tiny Striped Dawnsaber',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81016; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4730 AND `item`=900117; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4730,0,900117,0,0,0,12340);

-- Red Skeletal Horse -> Reins of the Tiny Red Skeletal Horse (Zachariah Post)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90019;
DELETE FROM `creature_template` WHERE `entry`=90019;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=11153;
UPDATE `swp_mount_creature` SET `entry`=90019,`name`='Tiny Red Skeletal Horse'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90019,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=11153;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=13331;
UPDATE `swp_mount_item` SET `entry`=900118,`name`='Reins of the Tiny Red Skeletal Horse',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81017; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4731 AND `item`=900118; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4731,0,900118,0,0,0,12340);

-- Blue Skeletal Horse -> Reins of the Tiny Blue Skeletal Horse (Zachariah Post)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90020;
DELETE FROM `creature_template` WHERE `entry`=90020;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=11154;
UPDATE `swp_mount_creature` SET `entry`=90020,`name`='Tiny Blue Skeletal Horse'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90020,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=11154;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=13332;
UPDATE `swp_mount_item` SET `entry`=900119,`name`='Reins of the Tiny Blue Skeletal Horse',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81018; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4731 AND `item`=900119; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4731,0,900119,0,0,0,12340);

-- Brown Skeletal Horse -> Reins of the Tiny Brown Skeletal Horse (Zachariah Post)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90021;
DELETE FROM `creature_template` WHERE `entry`=90021;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=11155;
UPDATE `swp_mount_creature` SET `entry`=90021,`name`='Tiny Brown Skeletal Horse'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90021,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=11155;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=13333;
UPDATE `swp_mount_item` SET `entry`=900120,`name`='Reins of the Tiny Brown Skeletal Horse',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81019; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4731 AND `item`=900120; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4731,0,900120,0,0,0,12340);

-- Black Skeletal Horse -> Reins of the Tiny Black Skeletal Horse (Zachariah Post)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90001;
DELETE FROM `creature_template` WHERE `entry`=90001;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=34238;
UPDATE `swp_mount_creature` SET `entry`=90001,`name`='Tiny Black Skeletal Horse'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90001,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=34238;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=46308;
UPDATE `swp_mount_item` SET `entry`=900100,`name`='Reins of the Tiny Black Skeletal Horse',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=80865; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=4731 AND `item`=900100; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (4731,0,900100,0,0,0,12340);

-- Whistle of the Emerald Raptor -> Reins of the Tiny Emerald Raptor (Zjolnir)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90022;
DELETE FROM `creature_template` WHERE `entry`=90022;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=6075;
UPDATE `swp_mount_creature` SET `entry`=90022,`name`='Tiny Emerald Raptor'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90022,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=6075;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8588;
UPDATE `swp_mount_item` SET `entry`=900121,`name`='Reins of the Tiny Emerald Raptor',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81020; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=7952 AND `item`=900121; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (7952,0,900121,0,0,0,12340);

-- Whistle of the Turquoise Raptor -> Reins of the Tiny Turquoise Raptor (Zjolnir)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90023;
DELETE FROM `creature_template` WHERE `entry`=90023;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=7707;
UPDATE `swp_mount_creature` SET `entry`=90023,`name`='Tiny Turquoise Raptor'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90023,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=7707;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8591;
UPDATE `swp_mount_item` SET `entry`=900122,`name`='Reins of the Tiny Turquoise Raptor',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81021; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=7952 AND `item`=900122; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (7952,0,900122,0,0,0,12340);

-- Whistle of the Violet Raptor -> Reins of the Tiny Violet Raptor (Zjolnir)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90024;
DELETE FROM `creature_template` WHERE `entry`=90024;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=7708;
UPDATE `swp_mount_creature` SET `entry`=90024,`name`='Tiny Violet Raptor'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90024,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=7708;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8592;
UPDATE `swp_mount_item` SET `entry`=900123,`name`='Reins of the Tiny Violet Raptor',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81022; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=7952 AND `item`=900123; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (7952,0,900123,0,0,0,12340);

-- Red Mechanostrider -> Reins of the Tiny Red Mechanostrider (Milli Featherwhistle)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90025;
DELETE FROM `creature_template` WHERE `entry`=90025;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=7739;
UPDATE `swp_mount_creature` SET `entry`=90025,`name`='Tiny Red Mechanostrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90025,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=7739;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8563;
UPDATE `swp_mount_item` SET `entry`=900124,`name`='Reins of the Tiny Red Mechanostrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81023; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=7955 AND `item`=900124; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (7955,0,900124,0,0,0,12340);

-- Blue Mechanostrider -> Reins of the Tiny Blue Mechanostrider (Milli Featherwhistle)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90026;
DELETE FROM `creature_template` WHERE `entry`=90026;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=7749;
UPDATE `swp_mount_creature` SET `entry`=90026,`name`='Tiny Blue Mechanostrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90026,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=7749;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=8595;
UPDATE `swp_mount_item` SET `entry`=900125,`name`='Reins of the Tiny Blue Mechanostrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81024; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=7955 AND `item`=900125; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (7955,0,900125,0,0,0,12340);

-- Green Mechanostrider -> Reins of the Tiny Green Mechanostrider (Milli Featherwhistle)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90027;
DELETE FROM `creature_template` WHERE `entry`=90027;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=11147;
UPDATE `swp_mount_creature` SET `entry`=90027,`name`='Tiny Green Mechanostrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90027,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=11147;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=13321;
UPDATE `swp_mount_item` SET `entry`=900126,`name`='Reins of the Tiny Green Mechanostrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81025; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=7955 AND `item`=900126; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (7955,0,900126,0,0,0,12340);

-- Unpainted Mechanostrider -> Reins of the Tiny Unpainted Mechanostrider (Milli Featherwhistle)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90028;
DELETE FROM `creature_template` WHERE `entry`=90028;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=10180;
UPDATE `swp_mount_creature` SET `entry`=90028,`name`='Tiny Unpainted Mechanostrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90028,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=10180;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=13322;
UPDATE `swp_mount_item` SET `entry`=900127,`name`='Reins of the Tiny Unpainted Mechanostrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81026; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=7955 AND `item`=900127; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (7955,0,900127,0,0,0,12340);

-- Red Hawkstrider -> Reins of the Tiny Red Hawkstrider (Winaestra)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90029;
DELETE FROM `creature_template` WHERE `entry`=90029;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=19280;
UPDATE `swp_mount_creature` SET `entry`=90029,`name`='Tiny Red Hawkstrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90029,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=19280;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=28927;
UPDATE `swp_mount_item` SET `entry`=900128,`name`='Reins of the Tiny Red Hawkstrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81027; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=16264 AND `item`=900128; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (16264,0,900128,0,0,0,12340);

-- Blue Hawkstrider -> Reins of the Tiny Blue Hawkstrider (Winaestra)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90030;
DELETE FROM `creature_template` WHERE `entry`=90030;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=20220;
UPDATE `swp_mount_creature` SET `entry`=90030,`name`='Tiny Blue Hawkstrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90030,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=20220;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=29220;
UPDATE `swp_mount_item` SET `entry`=900129,`name`='Reins of the Tiny Blue Hawkstrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81028; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=16264 AND `item`=900129; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (16264,0,900129,0,0,0,12340);

-- Black Hawkstrider -> Reins of the Tiny Black Hawkstrider (Winaestra)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90031;
DELETE FROM `creature_template` WHERE `entry`=90031;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=20222;
UPDATE `swp_mount_creature` SET `entry`=90031,`name`='Tiny Black Hawkstrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90031,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=20222;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=29221;
UPDATE `swp_mount_item` SET `entry`=900130,`name`='Reins of the Tiny Black Hawkstrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81029; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=16264 AND `item`=900130; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (16264,0,900130,0,0,0,12340);

-- Purple Hawkstrider -> Reins of the Tiny Purple Hawkstrider (Winaestra)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90032;
DELETE FROM `creature_template` WHERE `entry`=90032;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=20217;
UPDATE `swp_mount_creature` SET `entry`=90032,`name`='Tiny Purple Hawkstrider'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90032,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=20217;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=29222;
UPDATE `swp_mount_item` SET `entry`=900131,`name`='Reins of the Tiny Purple Hawkstrider',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81030; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=16264 AND `item`=900131; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (16264,0,900131,0,0,0,12340);

-- Brown Elekk -> Reins of the Tiny Brown Elekk (Torallius the Pack Handler)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90033;
DELETE FROM `creature_template` WHERE `entry`=90033;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=19658;
UPDATE `swp_mount_creature` SET `entry`=90033,`name`='Tiny Brown Elekk'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90033,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=19658;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=28481;
UPDATE `swp_mount_item` SET `entry`=900132,`name`='Reins of the Tiny Brown Elekk',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81031; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=17584 AND `item`=900132; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (17584,0,900132,0,0,0,12340);

-- Purple Elekk -> Reins of the Tiny Purple Elekk (Torallius the Pack Handler)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90034;
DELETE FROM `creature_template` WHERE `entry`=90034;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=20847;
UPDATE `swp_mount_creature` SET `entry`=90034,`name`='Tiny Purple Elekk'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90034,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=20847;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=29743;
UPDATE `swp_mount_item` SET `entry`=900133,`name`='Reins of the Tiny Purple Elekk',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81032; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=17584 AND `item`=900133; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (17584,0,900133,0,0,0,12340);

-- Gray Elekk -> Reins of the Tiny Gray Elekk (Torallius the Pack Handler)
DELETE FROM `creature_template_model` WHERE `CreatureID`=90035;
DELETE FROM `creature_template` WHERE `entry`=90035;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_creature`; CREATE TEMPORARY TABLE `swp_mount_creature` LIKE `creature_template`;
INSERT INTO `swp_mount_creature` SELECT * FROM `creature_template` WHERE `entry`=20846;
UPDATE `swp_mount_creature` SET `entry`=90035,`name`='Tiny Gray Elekk'; REPLACE INTO `creature_template` SELECT * FROM `swp_mount_creature`; DROP TEMPORARY TABLE `swp_mount_creature`;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`) SELECT 90035,`Idx`,`CreatureDisplayID`,0.45,`Probability`,`VerifiedBuild` FROM `creature_template_model` WHERE `CreatureID`=20846;
DROP TEMPORARY TABLE IF EXISTS `swp_mount_item`; CREATE TEMPORARY TABLE `swp_mount_item` LIKE `item_template`;
INSERT INTO `swp_mount_item` SELECT * FROM `item_template` WHERE `entry`=29744;
UPDATE `swp_mount_item` SET `entry`=900134,`name`='Reins of the Tiny Gray Elekk',`description`='Teaches this tiny 40% speed mount.',`RequiredLevel`=10,`RequiredSkill`=762,`RequiredSkillRank`=50,`spellid_2`=81033; REPLACE INTO `item_template` SELECT * FROM `swp_mount_item`; DROP TEMPORARY TABLE `swp_mount_item`;
DELETE FROM `npc_vendor` WHERE `entry`=17584 AND `item`=900134; INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`) VALUES (17584,0,900134,0,0,0,12340);

